export const RANDOM_FACTS = [
    "Bees can sting other bees.",
    "Tigers have striped skin.", 
    "Dolphins were studied as war tools during the Cold War.",
    "Sea lions are the only animal that can clap to a beat.",
    "Koalas have unique fingerprints.",
    "Everyone's tongue print is different.",
    "Your brain uses 10 watts of energy to think.",
    "The average person spends two weeks sitting at traffic lights.",
    "The Hollywood sign in Los Angeles once said 'Hollywoodland'.",
    "Iceland grows 5 centimeters per year.",
    "Russia has 11 time zones within the country.",
    "The Sahara Desert can reach up to 136° C.",
    "Baby elephants suck on their trunks.",
    "It takes a sloth two to four weeks to digest food.",
    "Slugs have four noses.",
    "The heart of a shrimp is located in its head.",
    "Russia has more surface area than Pluto.",
    "The closest state in the United States to Africa is Maine.",
    "There are more people in California than in Canada.", 
    "Australia is 600km wider than the moon.",
    "A blind chameleon can still adjust to the colors of its environment.",
    "All clownfish are born male.",
    "A group of porcupines is called a prickle.",
    "The heaviest onion ever grown was 18 pounds.",
    "Ketchup was once sold as medicine.",
    "Only 5% of the ocean has been explored.",
    "You can hear rhubarb grow.",
    "Dolly Parton once entered a Dolly Parton lookalike contest and lost.",
    "There's a town in Norway called Hell.",
    "Honey doesn't need to be refrigerated and will never go bad.",
    "Carrots were originally purple.",
    "Raspberries are a member of the rose family.",
    "Broccoli contains more protein than a lot of meats.",
    "Humans are the only animals on earth with chins.",
    "Every two weeks, a language or dialect goes extinct.",
    "Dogs' sense of smell is 40 times more powerful than humans.",
    "Dogs have a dominant paw.",
    "Dogs' noses are like human fingerprints; each one is unique.",
    "Dolphins literally sleep with one eye open.",
    "Originally, vacuum cleaners were horse-drawn.",
    "An ostrich's eye is bigger than its brain.",
    "You can hear a blue whale's heartbeat from over 2 miles away.",
    "The Easter Island heads have bodies.",
    "The Spanish national anthem has no words.",
    "Venus is the only planet to spin clockwise.",
    "The unicorn is the national animal of Scotland.",
    "The Eiffel Tower can be 15 cm taller during the summer."
];
